blank_issues_enabled: false
contact_links:
  - name: Dúvidas Gerais
    url: https://github.com/JonasCGN/Projeto_Smart_Joy/discussions
    about: Use a aba de Discussões para perguntas e ideias não técnicas.